"""add vector

Revision ID: afe4d2843d94
Revises: de62ffe57eb5
Create Date: 2024-11-10 02:12:31.789334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe4d2843d94'
down_revision: Union[str, None] = 'de62ffe57eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_file_entry', sa.Column('vector', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stored_file_entry', 'vector')
    # ### end Alembic commands ###
