"""add topic

Revision ID: de62ffe57eb5
Revises: 22f33555a105
Create Date: 2024-11-10 01:42:32.875954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de62ffe57eb5'
down_revision: Union[str, None] = '22f33555a105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_files', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stored_files', 'topic')
    # ### end Alembic commands ###
